//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusLibary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusStationEntities : DbContext
    {
        private static BusStationEntities _context;

        public BusStationEntities()
            : base("name=BusStationEntities")
        {
        }

        public static BusStationEntities GetContext()
        {
            if (_context == null)
            {
                _context = new BusStationEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Route> Route { get; set; }
    }
}
