//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int ID_Driver { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int NumberRoute_ID { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
