//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBuilderEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_History
    {
        public int ID_Employee_History { get; set; }
        public string Object_Employee { get; set; }
        public string Status_Employee { get; set; }
        public System.DateTime DateTime_Employee { get; set; }
    }
}
