//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBuilderEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Research
    {
        public int ID_Research { get; set; }
        public string Name_Research { get; set; }
        public Nullable<int> ID_Result { get; set; }
        public int ID_Status { get; set; }
        public int ID_Laboratory { get; set; }
    
        public virtual Research_Laboratory Research_Laboratory { get; set; }
        public virtual Result_Research Result_Research { get; set; }
        public virtual Status_Research Status_Research { get; set; }
    }
}
