//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBuilder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaneBuilderEntities : DbContext
    {
        private static PlaneBuilderEntities _context;

        public PlaneBuilderEntities()
            : base("name=PlaneBuilderEntities")
        {
        }
    
        public static PlaneBuilderEntities GetContext()
        {
            if (_context == null)
            {
                _context = new PlaneBuilderEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment_Research_Laboratory> Appointment_Research_Laboratory { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Brigade> Brigades { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_History> Employee_History { get; set; }
        public virtual DbSet<Manufacturing_History> Manufacturing_History { get; set; }
        public virtual DbSet<Manufacturing_Process> Manufacturing_Process { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Type> Product_Type { get; set; }
        public virtual DbSet<Research> Researches { get; set; }
        public virtual DbSet<Research_Laboratory> Research_Laboratory { get; set; }
        public virtual DbSet<Result_Research> Result_Research { get; set; }
        public virtual DbSet<Status_Research> Status_Research { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
    }
}
