//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_Employee { get; set; }
        public string Surname_Employee { get; set; }
        public Nullable<int> ID_Brigade { get; set; }
        public int ID_Laboratory { get; set; }
        public int ID_Post { get; set; }
        public string Name_Employee { get; set; }
        public string Patronymic_Employee { get; set; }
        public int Salary_Employee { get; set; }
        public string Login_Employee { get; set; }
        public string Password_Employee { get; set; }
        public bool Status_Employee { get; set; }
    
        public virtual Brigade Brigade { get; set; }
        public virtual Research_Laboratory Research_Laboratory { get; set; }
        public virtual Post Post { get; set; }
    }
}
