//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID_Product { get; set; }
        public string Name_Product { get; set; }
        public int ID_Material { get; set; }
        public int ID_Type { get; set; }
        public int ID_Laboratory { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Research_Laboratory Research_Laboratory { get; set; }
        public virtual Product_Type Product_Type { get; set; }
    }
}
