//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext
    {
        private static BDEntities _context; 
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        public static BDEntities GetContext()
        {
            if (_context == null)
                _context = new BDEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Storage> Book_Storage { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Libary> Libaries { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Reader_Category> Reader_Category { get; set; }
        public virtual DbSet<Reading_Room> Reading_Room { get; set; }
        public virtual DbSet<Reading_Room_Readers> Reading_Room_Readers { get; set; }
        public virtual DbSet<ReadRoom_Storage> ReadRoom_Storage { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
    }
}
