//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID_Employee { get; set; }
        public string Full_Name_Emp { get; set; }
        public string Employee_Login { get; set; }
        public string Employee_Password { get; set; }
        public int Reading_Room_ID_E { get; set; }
    
        public virtual Reading_Room Reading_Room { get; set; }
    }
}
