//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadRoom_Storage
    {
        public int ID_ReadRoom_Storage { get; set; }
        public int Book_Storage_ID { get; set; }
        public int Reading_Room_ID_RRS { get; set; }
    
        public virtual Book_Storage Book_Storage { get; set; }
        public virtual Reading_Room Reading_Room { get; set; }
    }
}
