//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading_Room_Readers
    {
        public int ID_Reading_Room_Readers { get; set; }
        public int Reader_ID_RRR { get; set; }
        public int Reading_Room_ID_RRR { get; set; }
    
        public virtual Reader Reader { get; set; }
        public virtual Reading_Room Reading_Room { get; set; }
    }
}
