//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int ID_Subscription { get; set; }
        public int Num_Subscription { get; set; }
        public System.DateTime Start_Of_Use { get; set; }
        public System.DateTime End_Of_Use { get; set; }
        public int Reader_ID_S { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}
